run:
  timeout: 3m
  tests: true

linters:
  enable:
    - govet
    - gofmt
    - goimports
    - staticcheck
    - unused
    - errcheck
  disable:
    - typecheck

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
